### ISSUE TITLE
Scripts can't deal with spaces in path

### ISSUE THREAD

**Issue by troy0h** [dontna/SaintsRow2-Proton-Fixer#1]
![image](https://github.com/user-attachments/assets/3072e9f3-4ac5-478c-941e-65ec1b3b744a)
I ran the script from a folder in my downloads folder, called "New Folder" (since I didn't see a point in naming it for a temporary script), and it errors out, since it can't handle the path containing spaces

**Comment by dontna** [comment]
Hello troy0h!

First of all, thank you for opening an issue for a problem with my script! It really helps me create better scripts going forward!

Secondly, the issue here is that the bash shell uses spaces as a way to denote new arguments for functions; so it basically thinks you're trying to pass in the path "/home/troy0/Documents/New" then call an argument "Folder". This is something in the bash shell that I can't really fix in my script since if bash is passing in the arguments incorrectly, my script will use them incorrectly too!

I would recommend wrapping the path in quotes (" ") to prevent this in the future!
`./saintsrow2_fixer.sh "/home/troy0/Documents/New Folder"`

I will 100% check to see if there's any workaround I can do in the script, however can't promise anything.

P.S: Sorry for the long reply time, I barely check this GitHub account!
